/* Pre-build step: compile content/blog/*.md into src/content/posts.generated.js */
const fs = require('fs');
const path = require('path');
const BLOG_DIR = path.join(__dirname, '..', 'src', 'content', 'blog');
const OUT = path.join(__dirname, '..', 'src', 'content', 'posts.generated.js');

function parseFrontmatter(raw) {
  const match = /^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/.exec(raw);
  if (!match) return { meta: {}, body: raw };
  const [, fm, body] = match;
  const meta = {};
  fm.split('\n').forEach((line) => {
    const idx = line.indexOf(':');
    if (idx === -1) return;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    }
    meta[key] = val;
  });
  return { meta, body: body.trim() };
}

let files = [];
try { files = fs.readdirSync(BLOG_DIR).filter((f) => f.endsWith('.md')); }
catch (e) { console.warn('[build-blog] No blog dir yet.'); }

const posts = files.map((file) => {
  const raw = fs.readFileSync(path.join(BLOG_DIR, file), 'utf8');
  const { meta, body } = parseFrontmatter(raw);
  return {
    slug: meta.slug || file.replace(/\.md$/, ''),
    title: meta.title || 'Untitled',
    date: meta.date || '', excerpt: meta.excerpt || '',
    author: meta.author || 'ProfX Team',
    tags: Array.isArray(meta.tags) ? meta.tags : (meta.tags ? [meta.tags] : []),
    cover: meta.cover || '', body,
  };
});
posts.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
const banner = '// AUTO-GENERATED by scripts/build-blog.js — do not edit by hand.\n';
fs.writeFileSync(OUT, banner + 'const posts = ' + JSON.stringify(posts, null, 2) + ';\nexport default posts;\n');
console.log('[build-blog] Compiled ' + posts.length + ' post(s) -> posts.generated.js');

// ── Also generate public/sitemap.xml (static pages + every blog post) ──
const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const SITE = 'https://profx.website';
const staticPaths = ['/', '/product', '/contact', '/blog', '/privacy', '/terms', '/refund'];
const urls = [
  ...staticPaths.map((p) => ({ loc: SITE + p, priority: p === '/' ? '1.0' : '0.7' })),
  ...posts.map((p) => ({ loc: `${SITE}/blog/${p.slug}`, priority: '0.6', lastmod: p.date })),
];
const xml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map((u) =>
    '  <url>\n    <loc>' + u.loc + '</loc>\n' +
    (u.lastmod ? '    <lastmod>' + u.lastmod + '</lastmod>\n' : '') +
    '    <priority>' + u.priority + '</priority>\n  </url>'
  ).join('\n') +
  '\n</urlset>\n';
try {
  fs.writeFileSync(path.join(PUBLIC_DIR, 'sitemap.xml'), xml);
  console.log('[build-blog] Wrote sitemap.xml (' + urls.length + ' urls)');
} catch (e) {
  console.warn('[build-blog] Could not write sitemap.xml:', e.message);
}
